#!/bin/bash
#---------------------- uberscript2 environment variables ----------------------

export SPEECHROOT="/home/qfrency/speech"

export SPEECHPYTHON="$SPEECHROOT/speect/build/swig/python:$SPEECHROOT/frontend:$SPEECHROOT/modules"
export PYTHONPATH="$SPEECHPYTHON:$PYTHONPATH"

export SPEECHBIN="$SPEECHROOT/local/bin:$SPEECHROOT/misc"
export PATH="$SPEECHBIN:$PATH"

#-------------------------------------------------------------------------------
voice=`basename "$0"|cut -c18-`
#test if qfrency license is already accepted for this voice
test -f "$HOME"/.kies/."$voice"&&qfrency_accepted="yes"||qfrency_accepted="no"
if test "$qfrency_accepted" = "no"
then less -E -P"press space to continue" /home/qfrency/Qfrency_license.txt
read -p" Type yes to accept, no to decline " accepted
	test "$accepted" = "yes"&&echo $accepted > "$HOME"/.kies/."$voice"||accepted='no'
fi
if test "$accepted" = "no" 
then 	read -p"You cannot use $voice as you have not accepted its usage terms. Press enter to exit." refuse
	exit 1
fi

echo "Preparing for synthesis using $voice"
see --nopager "$1" > /tmp/synth.txt
fromdos /tmp/synth.txt
sinsplit.py /tmp/synth.txt $HOME/synth.txt 2> /dev/null
echo "starting synthesis"
txt2wav $voice $HOME/synth.txt 2> /dev/null
files=`ls $HOME/synth.txt_?.wav|wc -l`

let tel=1
ls $HOME/synth.txt_?.wav|sort|while read wavs;do
	mv $wavs "$1"_$tel.wav
	let tel=$tel+1
done
test $files -eq 1&&mv "$1"_1.wav "$1".wav	
rm /tmp/synth.txt
rm $HOME/synth.txt

