#!/bin/bash
#Released under GNU General Public License version 3, see the file COPYING for details.
check_for() {
if (which "$1" 2> /dev/null > /dev/null)
  then ok=0
  else ok=1
  fi
}
check_for pdftohtml
if (test $ok -eq 1)
 then echo $0 "requires pdftohtml which is not installed"
     read -t8 -p "press enter to exit" wag
       exit 1
fi

check_for pickafile
if (test $ok -eq 1)
 then echo $0 "requires pickafile which is not installed"
     read -t8 -p "press enter to exit" wag
       exit 1
fi
check_for lynx
if (test $ok -eq 1)
 then echo $0 "requires lynx which is not installed"
     read -t8 -p "press enter to exit" wag
       exit 1
fi
test $# -lt 1&&echo "you must give me a pdf file to convert"&&exit
mkdir "$1".converted
cd "$1".converted
html=`echo "$1"|sed s/.pdf/.html/i`
pdftohtml -q ../"$1" $html
cd ..


lynx "$1".converted/"$html"
