#!/bin/bash
#Released under GNU General Public License version 3, see the file COPYING for details.
# LibreOffice calc wrapper script for use with pickafile
# kies_lo_calc can run without the menu, but it has to run as the command argument to startx,
# so pickafile tries to send its file argument to startx instead of sending it to kies_lo_calc.
# This wrapper fixes this problem.

check_for() {
if (which "$1" 2> /dev/null > /dev/null)
  then ok=0
    else ok=1
      fi
      }
      check_for startx
      if (test $ok -eq 1)
       then echo $0 "requires xinit which is not installed"
            read -t8 -p "press enter to exit" wag
                   exit 1
                   fi
                   
      check_for lwm
      if (test $ok -eq 1)
       then echo $0 "requires lwm which is not installed"
            read -t8 -p "press enter to exit" wag
                   exit 1
                   fi
                   
                   check_for orca
                   if (test $ok -eq 1)
                    then echo $0 "requires orca which is not installed"
                         read -t8 -p "press enter to exit" wag
                                exit 1
                                fi
                                
      check_for libreoffice
      if (test $ok -eq 1)
       then echo $0 "requires libreoffice which is not installed"
            read -t8 -p "press enter to exit" wag
                   exit 1
                   fi
                   
test -f "$1" || touch "$1"
startx $(which kies_lo_calc) "$1" >& /dev/null
test -s "$1" || rm -f "$1"
