#!/bin/bash
#Released under GNU General Public License version 3, see the file COPYING for details.
check_for() {
if (which "$1" 2> /dev/null > /dev/null)
  then ok=0
  else ok=1
  fi
}
check_for mplayer
if (test $ok -eq 1)
 then echo -e $0 "requires mplayer which is not installed.\n"
  read -t8 -p"Press enter to exit" wag
fi

eject /dev/dvd
read -p "place the DVD in the drive and close it." wag
mplayer -really-quiet   -vo null -dvd-Device /dev/dvd dvd://1
eject /dev/dvd
