#!/bin/bash
#Released under GNU General Public License version 3, see the file COPYING for details.
test $# -lt 1&&echo "usage: $0 <audio file>|<directory>"&&exit
test -d "$1"&&d='y'
test -f "$1"&&d='n'
function split_filename() {
	ext=`echo "$line"|rev|cut -s -f1 -d'.'|rev|dd conv=lcase 2> /dev/null`
	filename=`echo "$line"|rev|cut -f2- -d'.'|rev`
}

if test "$d" = 'y'
	then calledwith=`basename "$0"|cut -c6-|cut -f1 -d'2'`
	if test "$calledwith" != "any"
		then matchext=$calledwith
	else if test $# -ge 2
		then matchext=`echo "$2"|dd conv=lcase 2> /dev/null`
		else echo "$1 is a directory, thus a file extention must be provided, to which the conversions can be restricted, exitting"&&exit 1
		fi
	fi
	ls "$1"|while read line;do
		split_filename
		if test "$ext" = "$matchext"
			then echo "converting $line"
			if test "$matchext" = "wav"
			  then sox "$1"/"$line" "$1/$filename".mp3
			  echo "using sox for wav"
			else
		mplayer -noconsolecontrols -novideo -really-quiet -vc null -vo null -ao pcm:file="$1"/tmp.wav "$1/$line" 2> /dev/null&&lame -S -h "$1"/tmp.wav "$1/$filename".mp3||echo failled
			fi
		test -e "$1"/tmp.wav&&rm "$1"/tmp.wav
	else echo "skipping $line"
	fi
	done

else line="$1"
		split_filename
			mplayer -noconsolecontrols -novideo -really-quiet -vc null -vo null -ao pcm:file=tmp.wav "$line" 2> /dev/null&&lame -S -h tmp.wav "$filename".mp3||echo failled
fi

