#!/usr/bin/python
import sys
voicepath='/usr/share/speect_voices/'
default_voice='john2'
if len(sys.argv) == 1:
  print 'Usage: '+sys.argv[0]+' [<voicename>] <textfile>'
  exit
  
#sys.path.append("/home/wvdwalt/speech/speect_build/swig/python")
import speect, speect.audio, speect.audio_riff, wave
stem=default_voice
if len(sys.argv) == 3:
  filename=sys.argv[2]
  stem=sys.argv[1]
if len(sys.argv) == 2:
  filename=sys.argv[1]

v=speect.SVoice(voicepath+stem+"/voice.hts.json")
#v.features['rate']=1.0
#v.features['half-tone']=0.0
#v.features['volume']=0.5
progress=0.00
f=open(filename)
o=wave.open(filename+'.wav', 'wb')
o.setnchannels(1)
#o.setsampwidth(2)
o.setframerate(16000)
o.setparams((1, 2, 16000, 40480, 'NONE', 'not compressed'))
lines=f.readlines()
totlines=len(lines)
currentline=1.0
res=1

for line in lines:
  if len(line)==0 or line.isspace():
    continue
  u=v.synth(line)
  a=u.features['audio']
  w=a.get_audio_waveform()
  b=w['samples']
  o.writeframes(b)
  progress=(currentline/totlines)*100
  currentline=currentline+1
  oures=res
  res=int(progress)%10
  if oures != 0 and res==0:
    print int(progress)," percent"
  
f.close()
o.close()
