#!/bin/bash
loadkeys << EOF

alt keycode 103 = KeyboardSignal
keycode 59 = F1 F13 F25
keycode 60 = F2 F14 F26
keycode 61 = F3 F15 F27
keycode 62 = F4 F16 F28
keycode 63 = F5 F17 F29
keycode 64 = F6 F18 F30
keycode 65 = F7 F19 F31
keycode 66 = F8 F20 F32
              keycode 67 = F9 F21 F33
string F21 = "\033[35~"                                          
              keycode 68 = F10 F22 F34
string F22 = "\033[36~"                                          
              keycode 69 = F11 F23 F35
string F23 = "\033[37~"                                          
              keycode 70 = F12 F24 F36
string F24 = "\033[38~"                                          
string F25 = "\00442"
string F26 = "\00443"
string F27 = "\00444"
string F28 = "\00445"
string F29 = "\00446"
string F30 = "\00447"
string F31 = "\00450"
string F32 = "\00451"
string F33 = "\00452"
string F34 = "\00453"
string F35 = "\00454"
string F36 = "\00455"
                                          
EOF

