#!/bin/bash
#Released under GNU General Public License version 3, see the file COPYING for details.

runme='enter'
down='down'
up='up'
quit='escape'
if [[ $# -lt 1 ]]; then
echo "Usage: kies <file_name>"
     echo "where file name is the name of the menu you want to call up."
    echo "If you do not yet have a menu to call, use newmenu without arguments"
       echo " to create an empty menu in $HOME/.kies/main.txt"
      exit 0
fi

# Check for and possibly create the kies directory.
[[ -d "$HOME/.kies" ]] || mkdir -p "$HOME/.kies"

# Get the number of choices available to the user from the current menu.
optionCount=$(wc -l "$HOME/.kies/$1.txt" | cut -f1 -d ' ')
do_hot_command() {
# Check for, and create if missing, the hot_commands.txt file.
[[ -e "$HOME/.kies/hot_commands.txt" ]] || touch "$HOME/.kies/hot_commands.txt"
hotcommands=$(wc -l "$HOME/.kies/hot_commands.txt" | cut -f1 -d ' ')
hotline=$(echo "$wag" | cut -c2-)
if [[ $hotline -gt $hotcommands ]]; then
echo "$wag not assigned"
return
fi
$(sed -n "$hotline"p "$HOME/.kies/hot_commands.txt" | cut -f2- -d',')
}

say_hot_command() {
[[ -e "$HOME/.kies/hot_commands.txt" ]] || touch "$HOME/.kies/hot_commands.txt"
hotcommands="$(wc -l "$HOME/.kies/hot_commands.txt" | cut -f1 -d ' ')"
hotline=$(echo "$wag" | cut -c8-)
if [[ $hotline -gt $hotcommands ]]; then
echo "$wag not assigned"
return
fi
sed -n "$hotline"p "$HOME/.kies/hot_commands.txt" | cut -f1 -d ','
}

echo "you have $optionCount choices.  up/down arrows to select, enter to run, escape to quit"
i=1
oldpressed=""

while [[ $i -le $optionCount ]]; do
lyn=$(sed -n "$i"p "$HOME/.kies/$1.txt")
desc="$(echo "$lyn" | cut -f1 -d ',')"
command="$(echo "$lyn" | cut -f2- -d ',')"
echo -n "$desc"

wag=$(catchkey)
# Run the command connected to the function keys f1-f12
if [[ "$wag" =~ ^f[1-9]|10|11|12$ ]]; then
do_hot_command
fi
if [[ "$wag" =~ ^shift_f[1-9]|10|11|12$ ]]; then
say_hot_command
fi

 
if [[ "$wag" == "$runme" ]]; then
$($command)
fi

pressed=$wag
if [[ "$pressed" != "$oldpressed" ]]; then
oldpressed=$pressed
hit=-1
unset hk
mapfile -t hk < <(cut -c1 "$HOME/.kies/$1.txt" | grep -Fn "$pressed" | cut -f1 -d':')
hkmax=0
while [[ -n "${hk[$hkmax]}" ]]; do
 ((hkmax++))
 done
 ((hkmax--))
fi

if [[ $hit -lt $hkmax ]]; then
hit=$((hit + 1))
else
hit=0
fi

if [[ -n "${hk[$hit]}" && "$wag" != "$runme" ]]; then
i=${hk[$hit]}
 fi


[[ "$wag" == "$up" ]] && ((i--))
[[ $i -lt 1 ]] && i=$optionCount
[[ "$wag" == "$down" ]] && ((i++))
[[ $i -gt $optionCount ]] && i=1
[[ "$wag" == "$quit" ]] && i=$((optionCount+2))
clear
done
